### ISSUE TITLE
Use Typescript as compiler

### ISSUE THREAD

**Issue by rodneysantos** [tj/node-migrate#108]
Hi everyone,

Is there an example usage of typescript as compiler? I already tried different suggestions from my question here in [stackoverflow](https://stackoverflow.com/q/49031585/5553575) but with no luck.

Any help is much appreciated :smile:

**Comment by wesleytodd** [comment]
There was some recent discussion around this that might help you.  https://github.com/tj/node-migrate/pull/105

We need to revamp that functionality to stay in line with the popular compiler modules, but for now you can wrap it in a file in your project like this:

```javascript
require('ts-node').register({ ... })
```

Then call `$ migrate --compiler=./my-compiler.js`.

**Comment by rodneysantos** [comment]
Thank you @wesleytodd I'll try that :smile:

**Comment by wesleytodd** [comment]
I will close this, but feel free to re-open it you have any other issues.

**Comment by jmjpro** [comment]
I think this issue should be reopened. I haven't had a luck with it. I'm using node 8.9.4 on mac os/x. A working example would huge here!

I tried 
yarn migrate up --compiler="ts-node/register"
```
/Users/joshua/Projects/elminda/offering-migration/node_modules/migrate/lib/register-compiler.js:11
  if (mod[0] === '.') mod = path.join(process.cwd(), mod)
         ^

TypeError: Cannot read property '0' of undefined
```
yarn migrate up --compiler="ts:ts-node/register"
```
/Users/joshua/Projects/elminda/offering-migration/node_modules/migrate/lib/register-compiler.js:12
  require(mod)({
              ^
TypeError: require(...) is not a function
``

I also received the require(...) is not a function when I defined a file ts_node_compiler.js with contents `require('ts-node/register');` and then ran `yarn migrate --compiler="ts:./ts_node_compiler.js" up`

**Comment by jmjpro** [comment]
I got it working with my external file ts_node_compiler.js by adding `module.exports = () => {}`, so the complete file is ```
require('ts-node/register');
module.exports = () => {}
```

**Comment by wesleytodd** [comment]
Ok, so we clearly need better docs around this (as even I wrote the command incorrectly in my comment lol).  The current behavior is that the `--compiler` flag accepts the format `<extension>:<require-able module which registers the compiler>`.  So that last command is the most correct, but you need also need the module to export a function, which is called with an options argument.

See: https://github.com/tj/node-migrate/blob/master/lib/register-compiler.js#L12
