### ISSUE TITLE
integrate with travis ci to run tests for each pull request

### ISSUE THREAD

**Issue by jmjpro** [tj/node-migrate#116]
Travis CI integration must be setup by a repository administrator. Instructions are here: https://docs.travis-ci.com/user/getting-started/.

**Comment by wesleytodd** [comment]
If you open a PR with the travis config, I will go ahead and do that.  If not, I will look at adding it myself tomorrow when I am not at work.

**Comment by wesleytodd** [comment]
Added in #122.  Just need @tj to add me as owner or to have him enable it in travis.
