### ISSUE TITLE
does anyone else feel that this project deserves its own github organization?

### ISSUE THREAD

**Issue by jmjpro** [tj/node-migrate#119]
This project has been around for around over 6 years and @tj hasn't touched the code in many years. I recommend to move the project to its own organization. To the maintainers of this project, it's free and easy to create an organizational account at https://github.com/account/organizations/new. `migrate-node` is available as an organizaton name...

**Comment by LinusU** [comment]
I personally feel that it makes sense to move it once there is more than one repository that ties together, e.g. if we also started publishing adapters for different databases.

Is there a downside to having it on tj that I'm missing?

**Comment by jmjpro** [comment]
I guess it's mostly a marketing thing. It may make the project seem less
official when it's associated with one person's personal account.

**Comment by LinusU** [comment]
Yeah, that could be true 👍

**Comment by wesleytodd** [comment]
I agree mostly with @LinusU, but @jmjpro do you think pushing the marketing of the project is something you would like to help with?  If it is, then I could see some benefits.  Especially if you wanted to work on a docs/marketing site.  If not, I am comfortable leaving it as is.  

On the "less official" part, I see what you mean, but moving it to an org with only one repo could make it seem less official than people knowing it was started by TJ.  As silly as that is lol.

**Comment by jmjpro** [comment]
Yes, TJ's name is also good marketing. :-). Probably best to leave if it depends on my marketing skills as is my time is quite limited.
