### ISSUE TITLE
Unexpected error when start migrate

### ISSUE THREAD

**Issue by evgeny-s** [tj/node-migrate#124]
I'm trying to run migrate and faced with the error like this:
```bash
export ENV=local&&nbm exec migrate
```

![image](https://user-images.githubusercontent.com/2946193/39753668-52dc5a30-52c8-11e8-93c4-932bd6879634.png)

Can anybody help with that?
Thank you!

**Comment by evgeny-s** [comment]
Sorry, wrong place :)

**Comment by wesleytodd** [comment]
Reopened because you are still having this issue?  My guess would be a syntax error in your migration file.  I have a todo to get better logging, specifically to make debugging errors better, just haven't gotten to it, sorry.

**Comment by evgeny-s** [comment]
Yes, would be great. Because this is less info about the error. 
Thank you for doing this

**Comment by wesleytodd** [comment]
Well I didn't promise doing it now ;)

The simplest way to find a syntax error would be to run a linter on your migrations.  I would start with doing that if you cannot find the error manually.  If you have already resolved the issue can you close this?

**Comment by evgeny-s** [comment]
Once I resolve it, I'll close it.
