### ISSUE TITLE
Idea: Special force clean migration

### ISSUE THREAD

**Issue by wesleytodd** [tj/node-migrate#125]
I often find myself manually dropping tables because I am making a new migration and have an error in it which my `down` does not or cannot compensate for.  In development I really want just a nuclear option which is more forceful than `migrate up --clean` in that it does not run all the `down`'s, but instead it a full "drop all tables" kind of migration.

So my thought is that we add a special exception for `clean.js` which would be run instead of all the `down`'s if it exists on `--clean`.  It would of course need to be manually maintained and edited as you add migrations, but it would be a bit more simple to maintain than having all of the down's work in all situations.

What do people think of this idea?

cc: @LinusU @joaosa @tj

**Comment by LinusU** [comment]
Another approach would be for the adapters to know how to delete and create databases. That's how db-migrate works.

Then you can do `migrate drop` and `migrate create` to drop and create a new database from scratch.

So `migrate up --clean` would be equal to `migrate drop && migrate create && migrate up`. Maybe `migrate recreate` as a shorter verison?

**Comment by wesleytodd** [comment]
Hm, I am not sure how this is different from having a `create table` in the `up()` and a `drop table` in the `down()`?  The only difference is that db-migrate is *not* agnostic like this.  So I assume it tracks things like `create table` statements and knows how to undo them.  But for this tool it is important for it to *not* have that knowledge.

My current use case is basically just using this package with raw multi statement sql in the `up()`/`down()`.  If one of the statements fails, the ones before it succeeded, and thus the down will not run.  I know I can make a single migration for each table, but that would be annoying to maintain.

Is there a way you can think of where this package can solve this problem *without knowing about the underlying implementation*?

**Comment by LinusU** [comment]
The difference is that it drops the entire _database_, instead of working at the table level.

I think that dropping the entire database is better since it can be very easy to miss things in a manually maintained `clean`-migration. e.g. enums, increment-values, custom types and even entire tables.

That being said, it does depend on knowing something about the underlying implementation which might be a bad fit here. e.g. what would we do when using the default adapter that saves data in `.migrations`?

**Comment by wesleytodd** [comment]
Ahh, yeah I guess I didn't think of that.  That makes sense to drop the whole database in the case you describe.  I guess I didn't think of doing that since my migrations rely on the database being there because they operate on a docker container which creates the database for me.

Again though, what about if your migration is one that moves image files around, or migrates redis keys?  Neither of these are well solved by the current case for a clean down.

**Comment by wesleytodd** [comment]
Ok, so the more I think about this the more I think it is not a good idea.  I think that my initial migration should `CREATE DATABASE IF NOT EXISTS`, and then the down would `DROP DATABASE IF EXISTS`. 

And to my other scenarios, there are equivalents like `FLUSHALL` or `rm -rf .jpg`.  So any case can be handled without a special feature.
