### ISSUE TITLE
Uncaught Error: Cannot find module "." when using Webpack and programmatic usage

### ISSUE THREAD

**Issue by aguynamedben** [tj/node-migrate#126]
Hi, thanks for maintaining this great repo. I'm very optimistic it will fill an important need I have.

I'd like to manage migrations in an Electron app releases using node-migrate. I got command line usage working fine, but am having an issue where node-migrate can't load my migrations files. My app uses Electron, ES6, and Webpack (it's based on [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate))

My code:
```js
  nodeMigrate() {
    log.info('Starting migrations');

    // TODO: Update path for production
    const stateStore = path.join(process.cwd(), '.migrate');
    const migrationsDirectory = path.join(process.cwd(), 'migrations');

    log.info(`stateStore ${stateStore}`);
    log.info(`migrationsDirectory ${migrationsDirectory}`);

    const migrateConfig = {
      stateStore,
      migrationsDirectory,
    };

    migrate.load(migrateConfig, (error, set) => {
      if (error) {
        log.error(`Failed to load migrate config: ${error}`);
        throw error;
      }

      set.up((error) => {
        if (error) {
          log.error(`Running migrations failed: ${error}`);
          throw error;
        }
        log.info(`Migrations successfully ran!`);
      })
    });
  }
```

The log messages indicate the correct directories:
```
[14:45:24.307] [info] stateStore /Users/ben/code/tesla/.migrate
[14:45:24.307] [info] migrationsDirectory /Users/ben/code/tesla/migrations
```

When the migrations run, I get this error:
<img width="675" alt="developer_tools_-_file____users_ben_code_tesla_app_app_html" src="https://user-images.githubusercontent.com/107841/41182691-947e5436-6b2b-11e8-886a-dd5ee354beef.png">

Digging into the stacktrace, the code that has been executed in my environment is:
```js
      // Create migrations, keep a lookup map for the next step
      var migMap = {}
      var migrations = files.map(function (file) {
        // Try to load the migrations file
        var mod
        try {
          mod = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())
        } catch (e) {
          return fn(e)
        }

        var migration = new Migration(file, mod.up, mod.down, mod.description)
        migMap[file] = migration
        return migration
      })
```

The code as it's written in this repo is:
```js
      // Create migrations, keep a lookup map for the next step
      var migMap = {}
      var migrations = files.map(function (file) {
        // Try to load the migrations file
        var mod
        try {
          mod = require(path.join(migrationsDirectory, file))
        } catch (e) {
          return fn(e)
        }

        var migration = new Migration(file, mod.up, mod.down, mod.description)
        migMap[file] = migration
        return migration
      })
```

It seems that at compile time, Webpack (or Babel?) is attempting to rewrite the require() and it fails.

After doing some digging, I think it might be because the require() as written in the code uses an expression instead of a value. See this: https://github.com/webpack/webpack/issues/4921#issuecomment-342523044

My instinct would be to create a PR that changes:
```js
mod = require(path.join(migrationsDirectory, file))
```
to
```js
mod = require(`${path.join(migrationsDirectory, file)}`)
```
([this solution](https://github.com/webpack/webpack/issues/4921#issuecomment-357147299)) but this project itself isn't written in ES6.

Any direction you could provide on getting node-migrate working nicely with Webpack would be much appreciated. I'm not well-versed on require/import in JavaScript, and how it impacts require(), but I expect it's some misalignment of expectations between Webpack and node-migrate.

Thanks for your time. 🙏

**Comment by aguynamedben** [comment]
I'm going to try fixing this by changing the `require` to `import` similar to [how they did in umzug](https://github.com/sequelize/umzug/commit/d203cbe7521b9b36492c343667e214c88fbe0805#diff-410142b027abfe35d3351577b731ebcaL57). Will report back.

**Comment by domske** [comment]
In my case it solved the problem by removing `/umd` from import pathes. 
Search and replace all occurrences of `ionic-angular/umd` with `ionic-angular`.
I don't know why is `/umd` set on the pathes. And I'm sure it also working with `/umd`. 
The problem comes suddenly. In my case I renamed a few files in my sources.
But rebuilt incl. clean. Usually it works. This error (cannot find module ".") is rare but persistent.

**Comment by wesleytodd** [comment]
Hey, I am going to close this.  If in the future there is a solution to this, or other developments, please feel free to post or reopen.
