### ISSUE TITLE
Custom state storage should be documented better

### ISSUE THREAD

**Issue by MatthewSteel** [tj/node-migrate#127]
The README says,

>> As long as what goes in as `set` comes out the same on `load`, then you are good to go!

It should say something about what `set` actually looks like, because its shape says something about how users can persist it. Is it a string? Is it something the user can call `JSON.stringify` on, and restore with `JSON.parse`?

Reading the source, it looks like `set` is a `MigrationSet` object, and the `MigrationSet` has the `store` as a property. Should `load` return a `MigrationSet` object with a `store` as a property, then? It doesn't look like the `FileStore` default does anything like that, so I guess it's fine not to?

Also, some guidance should be provided about what `load` should return when no migrations have been run. Presumably `store` hasn't been run at all yet (unless it's called on `init`?) Is `null` ok? Should it be an empty object?

Reading the source, it looks like "An empty object should be a safe bet for an initial state, and serialising/deserialising `set` with `JSON.stringify`/`parse` should be ok`.

**Comment by wesleytodd** [comment]
Hey @MatthewSteel, thanks for the feedback.  Yes `set` which is passed to the store is a `MigrationSet` but really all it does is use the `migrations` and `lastRun` keys.  All `load` needs to return is those keys in an object.

I am not able to work on those docs at the moment but would love it if someone opened a PR expanding on them! *hint hint* ;) ;)

**Comment by wesleytodd** [comment]
Hey @cbesangeeth, the code for this is pretty straight forward: https://github.com/tj/node-migrate/blob/master/lib/file-store.js

Just do what that does, except instead of writing to a file, write to your database.  Hope that helps!

**Comment by dextervip** [comment]
How could I set default state storage class for CLI?

**Comment by wesleytodd** [comment]
There is no current way to set default options in the cli, just by passing the flag.  The way I usually setup my projects is by creating npm scripts for the different migration configurations I need.  For example, here is a block from the current project I am working on:

```
    "migrate-up": "PLE_EDITORIAL_PROMOTION_INIT_DB=true migrate up --env .env",
    "migrate-up-dev": "migrate up --env .env-dev --state-file='.migrate-dev'",
    "migrate-up-dev-clean": "migrate up --env .env-dev --state-file='.migrate-dev' --clean",
    "migrate-up-staging": "migrate up --env .env-staging --state-file='.migrate-staging'",
    "migrate-up-staging-clean": "migrate up --env .env-staging --state-file='.migrate-staging' --clean",
    "migrate-up-prod": "migrate up --env .env-prod --state-file='.migrate-prod'",
    "migrate-down": "migrate down --env .env",
```

**Comment by dextervip** [comment]
@wesleytodd Good hint! I got it working by passing migrate up --store="./lib/file-store/database-storage.js"

**Comment by qqilihq** [comment]
In case anyone wants to store his state in a MongoDB -- we’ve just made our solution available as an NPM module:

https://github.com/NodePit/node-migrate-state-store-mongodb

Feedback and contributions always welcome!

**Comment by wesleytodd** [comment]
That PR is merged.  Closing.

**Comment by killmenot** [comment]
Redis state store (Inspired by @qqilihq work)
https://www.npmjs.com/package/migrate-state-store-redis
