### ISSUE TITLE
Custom folder path for migration files

### ISSUE THREAD

**Issue by cbesangeeth** [tj/node-migrate#128]
How do i maintain my migaration files in custom location like `./migrations/foo/`

Documents say, 
`To create a migration, execute migrate create <title> with a title. By default, a file in ./migrations/ will be created.`

Since my application has multiple db's (currently postgres and redshift) and i want to maintain migrations files for different db's in my custom folders.

**Comment by wesleytodd** [comment]
For this you can use the `--migrations-dir <dir>` flag.

```
$ migrate --migrations-dir="./migrations/foo" create bar
```
