### ISSUE TITLE
migrate up returns typeerror 

### ISSUE THREAD

**Issue by owenljn** [tj/node-migrate#135]
```
return Promise.all([
                 ^

TypeError: Cannot read property 'all' of undefined
    at Migration.exports.up (/Users/owenlu/Documents/Funnelytics/shared-data/migrations/20161114142438_organizations.js:3:18)
    at next (/usr/local/lib/node_modules/migrate/lib/migrate.js:35:43)
    at migrate (/usr/local/lib/node_modules/migrate/lib/migrate.js:76:3)
    at up (/usr/local/lib/node_modules/migrate/bin/migrate-up:119:3)
    at /usr/local/lib/node_modules/migrate/bin/migrate-up:98:36
    at /usr/local/lib/node_modules/migrate/index.js:61:5
    at /usr/local/lib/node_modules/migrate/lib/load-migrations.js:72:7
    at FSReqWrap.oncomplete (fs.js:135:15)
```

Hi, I'm trying to run 'migrate up' command, but I got this error, I have "Promise.all" in my code though

**Comment by owenljn** [comment]
hey thanks for the reply, I'm not using promise polyfill, and the node version is 8.9.4 which I have to use in order for the code to work

**Comment by wesleytodd** [comment]
Can you post more of your code?  The error is in `shared-data/migrations/20161114142438_organizations.js`.  Can you post that file?

**Comment by owenljn** [comment]
Sure, here you go
```

exports.up = (knex, Promise) => {
  return Promise.all([
    knex.schema.createTableIfNotExists('organizations', (t) => {
      t.uuid('id').primary();
      t.string('name', 256).notNullable();
      t.timestamps();
    })
  ]);
};

exports.down = (knex, Promise) => {
  return Promise.all([
    knex.schema.dropTableIfExists('organizations')
  ]);
};

```

I have a whole bunch of other migration files, they all have the same problem

**Comment by wesleytodd** [comment]
Ok, well that is the reason.  The migration is not called with `Promise` or `knex` like you have here.  It is called only with a `next` function.  Are you wanting to wrap all your migrations in something which provides those arguments?

**Comment by owenljn** [comment]
Yup, and I just got this problem solved using knex combined with migrate, now it works, thank you for the effort!
