### ISSUE TITLE
Storing different migration states for different server

### ISSUE THREAD

**Issue by AakashGfude** [tj/node-migrate#143]
Hi,

I was setting up migration scripts for my mongodb database and have successfully run the migration script in the localhost. Now I want to run it in development. What do you suggest is the best minimal way to do it. 
Maybe like putting .migrate file in .gitignore so that every environment/system has its own instance.
Also I should include this migrate command in my npm build script right?
What do you suggest.
Thanks.

**Comment by wesleytodd** [comment]
Hey @AakashGfude,

There are many ways you could set this up depending on how it best integrates to your setup.  The way I have been running lately is to have multiple `.migrate` files, one for each environment (ex. `.migrate-local`).  With that file setup you can either ignore `.migrate*` or commit them to keep the state in version control.

You can also use a storage engine to store it in the database next to your data, we have an [example of this here](https://github.com/tj/node-migrate/blob/master/examples/custom-state-storage/custom-state-storage.js).

**Comment by AakashGfude** [comment]
Thanks @wesleytodd for the ideas.
