### ISSUE TITLE
--migrations-dir flag should allow absolute path

### ISSUE THREAD

**Issue by akivajgordon** [tj/node-migrate#148]
## Action

```sh
migrate create --migrations-dir=/tmp/foo bar
```

## Expected behavior

A migration file `<TIMESTAMP>-bar.js` would be created in the absolute path `/tmp/foo`.

## Observed behavior

An error was thrown saying that the directory `$PROJECT_PATH/tmp/foo` does not exist, e.g.:

```
  Template generation error : ENOENT: no such file or directory, open '/Users/akivajgordon/my-proj/tmp/foo/1550508843869-bar.js'
```

Notice that the path `/tmp/foo` is being resolved as a _subdirectory_ of the project, even though I specified the path as an absolute path. I assume this is not the intended behavior. Even the existing code makes it seem like it wasn't the intended behavior (in lib/template-generator.js): 

```js
    // Ensure migrations directory exists
    mkdirp(migrationsDirectory, function (err) {
      // ...
      // Fix up file path
      var p = path.join(process.cwd(), migrationsDirectory, slug(formattedDate + (name ? '-' + name : '')) + extension)

      // ...
    })

```

The path passed to `mkdirp` is now completely irrelevant from the path that actually gets resolved.

**Comment by wesleytodd** [comment]
Closing this in favor of the PR.
