### ISSUE TITLE
some mongodb commands dont work here which works in mongo shell

### ISSUE THREAD

**Issue by AakashGfude** [tj/node-migrate#152]
Hi, I am not able to save the entries in a db using forEach, I am not sure if the `return` statments are correct. It works perfectly fine in mongo shell. My code is :- 

```
let User = require('../models/User');
return mongoose.connect(config.url, options).then(db => {
              // perform db operations here
              return  User.find({ $and: [{ currentProvider: "Github" }, { avatar: { $regex: /^.*[^s=75]$/ } }] 
         }).forEach(function (e, i) { console.log(e); e.avatar = e.avatar + '&s=50'; User.save(e);});
    })
    .then(() => {
      mongoose.close()
      return next()
    })
    .catch(err => next(err))
}
```

Thank you

**Comment by wesleytodd** [comment]
Hi @AakashGfude, nothing in this code is part of dealing with migrations.  Maybe you meant to post this in another repo? The mongoose repo maybe?

**Comment by stackprogramer** [comment]
No, your migrate package has a problem. we too can not work with migrate alongside mongo driver.
https://github.com/tj/node-migrate/issues/193
