### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by olegk101** [tj/node-migrate#154]
Hey,
I'd like to submit a PR with a couple of improvements to the documentation

1. It's a bit confusing that when up/down function is async the next callback shouldn't be called
2. Can we add --migrations-dir to the cli api documentation to allow passing a custom folder location?  "migrate create some-migration --migrations-dir custom-folder/migrations"

**Comment by wesleytodd** [comment]
That would be awesome!! When you open it feel free to close this.

For the migrations dir, it is in the cli docs:

https://github.com/tj/node-migrate/blob/master/bin/migrate-create#L15

Where is it missing?

**Comment by olegk101** [comment]
Ah, I couldn't find.
Do you mind if I add this part to README.md?

**Comment by wesleytodd** [comment]
Yes please :)
