### ISSUE TITLE
node hangs up a for a moment after migrations

### ISSUE THREAD

**Issue by SulaimanAlabbar** [tj/node-migrate#163]
Here's a function I'm using to reset my database, for tests.

```js
function resetDb() {
  console.log("Resetting database");

  migrate.load(
    {
      stateStore: path.join(process.cwd(), ".migrate"),
      migrationsDirectory
    },
    (err, set) => {
      if (err) {
        console.error(err);
      }

      set.down(err2 => {
        if (err2) {
          console.error(err2);
        }

        set.up(err3 => {
          if (err3) {
            console.error(err3);
          }

          console.log("Database reset");
        });
      });
    }
  );
}
```
Hangs up for ten seconds after finishing its work:
![Peek 2019-08-09 08-25](https://user-images.githubusercontent.com/43919657/62756297-d80f3900-ba7f-11e9-9758-06aad4e52127.gif)

Since this is way too slow, I'm using this instead:

```js
const migrateCommand = `${path.join(
  __dirname,
  "../"
)}node_modules/migrate/bin/migrate`;

module.exports = () => {
  execFileSync("node", [
    migrateCommand,
    "down",
    `--migrations-dir=${migrationsDirectory}`
  ]);
  execFileSync("node", [
    migrateCommand,
    "up",
    `--migrations-dir=${migrationsDirectory}`
  ]);
};
```

Which is acceptable for now, but won't be when I have more tests.

It's not that my database is big, right now I only have two tables.

**Comment by wesleytodd** [comment]
I am a bit confused by this report.  Are saying that it closes quickly when you run as a sub process but not when you run it directly in the main process?  

In order to debug this I would probably need more context.  What is calling this method? What do your migrations do? My mostly likely idea would be a database connection not being released, and then having its keep alive timeout hit.  But that is just conjecture without more context.

**Comment by SulaimanAlabbar** [comment]
Made a simple repo that shows what I mean.
https://github.com/SulaimanAlabbar/migrations-test

This is what happens when I run this script "npm run reset-db":
![Peek 2019-08-10 03-43](https://user-images.githubusercontent.com/43919657/62815390-1577d300-bb21-11e9-9c71-80c70621115f.gif)

**Comment by wesleytodd** [comment]
https://node-postgres.com/api/pool#pool.end

You need to call `pool.end`.  I am pretty sure this is not related to migrate.  If you can provide a more simple and clear test case which proves it is related to this package feel free to re-open this issue.
