### ISSUE TITLE
TypeError: Store is not a constructor ERROR

### ISSUE THREAD

**Issue by ceciliazcx** [tj/node-migrate#168]
Hi here,
First, I already read all the issue related with this Error. But no luck to fix it.

I wrote code with typescript. `migrate create` and `migrate up/down` with default state local save work fine. 
When I tried to custom state file. I got the error as following:

> var store = new Store(program.stateFile)
>             ^
> TypeError: Store is not a constructor
>     at Object.<anonymous> (\node_modules\migrate\bin\migrate-up:64:13)

The command I use is as following:

`migrate up --compiler=ts: ./migrations/ts-compiler.js --store=./migrations/db-store.ts `

db-store.ts is has simple structure as following:
```
class dbStore {
    constructor() {
        ....
    }

    connect() {
          ...
    }

    load(fn:any) {
        ...
        return xxx;
    }

    save(set:any, fn:any) {
       ...
        return xxx;
    }
}

export default dbStore;
```

Anyone could help? Thanks a lot.

**Comment by wesleytodd** [comment]
Hey, I didnt see this before, but @ceciliazcx with this code your export will be on `default`.  I would recommend not using ES Modules for this, there is no way to get it to work with today's implementation which requires the only export to be a function.

**Comment by luisrudge** [comment]
@wesleytodd I added a PR to make it work with default. Let me know if you need something else.
