### ISSUE TITLE
Migrate to `main`

### ISSUE THREAD

**Issue by wesleytodd** [tj/node-migrate#176]
@tj I need you to add me as owner on this.  I just pushed a release which rebases a bunch of things onto `main`.  I need to be an owner in order to change the default branch.

**Comment by wesleytodd** [comment]
@tj Can you help me out here?

**Comment by tj** [comment]
hmm I don't see anywhere in the UI to give more permissions, maybe because it's not in an org, but I updated the default branch to main

**Comment by wesleytodd** [comment]
There was one other reason I thought I needed owner, but I can't remember anymore.  But yeah, I went and dug around for it but couldn't find it either.  Would you be willing to move the repo into a new org?  I registered `@migratejs` where I was working on some new stuff for this.  We could move it there.

https://github.com/migratejs

**Comment by wesleytodd** [comment]
I sent you an invite to that org, if you want to move it I think you should be able to accept the invite and move it.  I could obviously just do it with a git push, but I think you can actually move it with all the issues and PRs intact.

**Comment by tj** [comment]
cool yea I'll try and remember to do that in the next few weeks, busy moving to a new place at the moment!

**Comment by wesleytodd** [comment]
No rush! I haven't been able to work on this in a while anyway.  And I understand moving, I just moved into an RV and it was *the worst*, so take your time, whenever you get to it!
