### ISSUE TITLE
setup/teardown

### ISSUE THREAD

**Issue by TrejGun** [tj/node-migrate#25]
Plz, add setup/teardown functions to open/close db connection before/after couple of migrations

**Comment by timlesallen** [comment]
+1

**Comment by geekytime** [comment]
:+1: - I would probably call them `before` and `after`, though.

These functions could also be used to alleviate the need for #29, as we could load our `.migrate` file from the DB in `before`, and store it in the db in `after`.

**Comment by wesleytodd** [comment]
I have two thoughts on this:

1. Use the new `store` as implemented in the new `1.x` branch.  Basically `store.load` is called before anything else, so you could initialize your db connections in there.
2. Expose more event hooks with cli flags like `--before="path/to/before.js"` and `--after="after.js"`

An example of number 1 would be:

```javascript
var mysql = require('mysql')
module.exports = MysqlStore
MysqlStore (configString) {
  this.db = mysql.createConneciton(configString)
}

MysqlStore.prototype.load = function (fn) {
  this.db.connect(function (err) {
    if (err) return fn(err)
    // load state from mysql, or even inherit this from the FileStore, call fn when done
    fn(null, state)
  })
}

MysqlStore.prototype.safe = function (set, fn) {
  // do save stuff, but save is called after each migration, so dont close db
}
```

It should work, and does not require any new api in the core module.  You could even set it up easily to expose a `db` singleton that all your running migrations could share.

Option number 2 is much more straight forward but means added api and complexity.  Would love to get opinions on which way to go.

**Comment by wesleytodd** [comment]
Since there is a lack of activity on this, closing.
