### ISSUE TITLE
Error running "down" command twice

### ISSUE THREAD

**Issue by mrosalesdiaz** [tj/node-migrate#33]
If I run "down" command twice. First time, it executes all migrations in reverse order and the second time it executes first migration, after that it always shown complete message.
Running "up" command after this, causes that first execution perform last migration and then in a second execution it runs all migrations in order.

Is this a normal behavior? Is there a way to rid of this problem?

Thank you in advance.

**Comment by LinusU** [comment]
@mrosalesdiaz, @hyzhak if I understood the issue correctly it has now been fixed as proven by the test in #53. Could you guys please verify that it works or demonstrate to me how to make it fail? Thanks!
