### ISSUE TITLE
middleware -- reatltime

### ISSUE THREAD

**Issue by ghost** [tj/node-migrate#35]
Hi TJ, have you created a way to integrate this into a web app module, so that when the server is restarted, deployed, etc, a middleware is triggered to run these?  I am using a host called modulus.io where you dont have SSH access to the server.

Just curious before I go and build one.

**Comment by LinusU** [comment]
This would be a lot easier with a more friendly api for developers, see #44.

**Comment by LinusU** [comment]
This is now fixed, take a look at the [api section of the readme](https://github.com/tj/node-migrate#api). If you want to run the migrations every time you start the server it would be as follows:

```javascript
var migrate = require('migrate');

migrate.load('migrations/.migrate', 'migrations').up(function (err) {
  if (err) throw err;

  console.log('The db is now up to date!');
});
```
