### ISSUE TITLE
first migrate create not running

### ISSUE THREAD

**Issue by morefromalan** [tj/node-migrate#38]
Running migration like so:
````
migrate create anamehere
````
Raises error:
````
migrate: error: Not enough arguments for command create: name not specified
ubuntu@ip-172-31-19-221:~/statblender$ migrate create
Usage: migrate create REPOSITORY_PATH NAME [--table=TABLE]
````
Just installed on ubuntu via: 
````    
npm install migrate
````

**Comment by LinusU** [comment]
I see two problems here.

1. You have not installed `migrate` globally, but instead installed it as `node_modules/.bin/migrate`. To install it globally you have to supply the `-g` flag to `npm install`.

2) It seems like you have installed `sqlalchemy-migrate` which also has a binary called `migrate`. Depending on your `$PATH` one of them will get called. Try and do `which migrate` to see which file will be executed.

To avoid both problems all together I would suggest to only install migrate locally. Start by installing migrate locally `npm install --save-dev migrate`. Then add the following to your `package.json`.

```javascript
"scripts": {
  "migrate": "migrate"
}
```

You can now run your migrations with `npm run-script migrate` and create new migrations with `npm run-script migrate -- create my-nice-migration`.
