### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by LinusU** [tj/node-migrate#50]
@tj I understand that you no longer maintain your Node.js projects and I was wondering if you would be interested in adding me as a collaborator to this repo. I have no plans for any drastic changes but I would like to ensure stability and close some of the bugs that are currently open. Thanks for your time.

My first order of business would be to merge in #47, #48, #49 and make sure that we can release them without any backwards-incompatible changes.

I'm [linusu](https://www.npmjs.com/~linusu) on npm.

**Comment by joaosa** [comment]
@LinusU Unfortunately I can't add you as a maintainer, but I merged your PRs :)

**Comment by LinusU** [comment]
@joaosa Sorry for late answer, I'm on vacation in NYC this week. Thanks for merging the requests so quickly!

Could you push a new patch release to npm? Thanks! :beers:

**Comment by tj** [comment]
@LinusU added!

**Comment by LinusU** [comment]
@tj Thank you! I'm `linusu` on npm if you want to give me push access there as well :)

**Comment by LinusU** [comment]
I now have push access to npm :)

**Comment by arxpoetica** [comment]
@LinusU @tj What is the status of this repo? I know you gave up Node many a moon ago, TJ, but are there plans to hand this useful utility off to anyone? I think it might be broken on the latest version(s) of Node.js (for some reason?). Been digging into it a little, but no go yet.

**Comment by LinusU** [comment]
I haven't seen any bug report on this being broken on the latest node, maybe I missed something? I'm still actively maintaining this and would be happy to merge PRs and/or look into any bugs that are present...

**Comment by arxpoetica** [comment]
I was wrong, sorry. It was something on my end. Sorry. False negative.
