### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by Jokero** [tj/node-migrate#52]
Some pull requests https://github.com/tj/node-migrate/issues/50 were merged :)

**Comment by LinusU** [comment]
Unfortunately I only got added as a maintainer on Github and not on npm.

ping @tj if you would like to fix this I'm [linusu](https://www.npmjs.com/~linusu) on npm :)

**Comment by Jokero** [comment]
@tj

**Comment by tamtakoe** [comment]
@tj please, add LinusU to npm maintainers or update npm package yourself

**Comment by LinusU** [comment]
I'm now added as maintainer and have published `0.2.1` with all the latest changes.

**Comment by Jokero** [comment]
Congratulations, @LinusU :) Thanks :+1:
