### ISSUE TITLE
is it possible to use with es6 syntax?

### ISSUE THREAD

**Issue by almeynman** [tj/node-migrate#59]
cannot make it work with es6 imports

**Comment by LinusU** [comment]
This is currently not possible, I think a good idea might be to solve it like mocha has.

```sh
migrate --compilers js:babel/register
```

**Comment by vayser** [comment]
you could look to this fork
https://github.com/jarvisaoieong/migration

**Comment by floo51** [comment]
Well you can use babel-cli to call migrate.

`./node_modules/.bin/babel-node ./node_modules/.bin/migrate`
