### ISSUE TITLE
Governance?

### ISSUE THREAD

**Issue by wesleytodd** [tj/node-migrate#71]
@LinusU & @joaosa

It looks like you two are the most "recent" large contributors.  Before I move forward, can you let me know what level of involvement you would like to have with moving forward?  I would be down with coming up with some guidelines/process if you want to be involved.  Or I can just take over and move it in the direction which my fork has been going, which adds features and in some cases breaks current functionality.  Let me know!

**Comment by joaosa** [comment]
@wesleytodd Great to see all your changes. I skimmed over https://github.com/tj/node-migrate/pull/70 and it's looking pretty good. I confess I am pretty happy about [standard](https://github.com/feross/standard). 

As for my involvement, I am willing to assist with whatever might be needed (e.g. review PRs, fix bugs, improve tests, close issues) and assume a more supportive role if needed.

I think it'd be a good idea to review and finally merge the PR. 
I should have some time to look into it soon.

@wesleytodd @LinusU How do you see this moving forward from here?

**Comment by wesleytodd** [comment]
Thanks @joaosa!  Glad to hear you would like to continue with the project, I was worried since it had sat dormant for so long people would not be interested.

As for that PR, it was really just my idea to get the ball rolling.  Now that I have the ability to move those contributions forward here, in the main repo, I would like to re-structure all of those commits so that they can be merged here on a piece by piece basis.  Starting with standard :)

Personally, I think it is always a good idea to have multiple people review the direction things are taking, as well as the implementation.  So my preference would be if all of the contributions I have staged on that branch get at least one of you to look at and review.  And I would prefer that that continue for other feature additions.

**Comment by joaosa** [comment]
@wesleytodd That sounds great. Breaking down the PR into smaller ones would make the process smoother :)

I second your thoughts on receiving feedback from others. I will be glad to help with that.

**Comment by szimek** [comment]
@wesleytodd Hey, quick question, because we're most likely going to need some kind of migration system very soon (like this week 😉 ) and this one looks like exactly what we need (thanks @tj!). Is there a list of changes you made in your fork and some docs how to use it? I'm not sure if it's better to use this version or your fork...

**Comment by wesleytodd** [comment]
Hey @szimek, you can check out the PR here: https://github.com/tj/node-migrate/pull/70

It is published here: https://www.npmjs.com/package/@wesleytodd/migrate

We are using the fork at my company in one part of our app, so it is reasonably safe to use.  I have been focusing more on the features than the docs, but my intent was to add those as I merged things into here.  I have a busy few weeks, so am not sure how quickly I will be getting everything broken out for PR's, but my goal is to have a `1.x` version asap.  I do not plan to continue working on the fork now that I can merge it all here, but if you start using the current version here there will certainly be breaking changes soon.

Hope that helps you make your decision on what to do.

**Comment by LinusU** [comment]
Awesome to see work happening on this @wesleytodd, I'd be happy to help review/merge/release or whatever is needed :)

I think that you should be added as a maintainer on Github and npm when we merge it as well 👍

**Comment by wesleytodd** [comment]
Going to close this since that 1.0 branch is pretty much ready to release and it seems like everyone is good with it.
