### ISSUE TITLE
The program 'migrate' can be found in the following packages

### ISSUE THREAD

**Issue by Gardezi1** [tj/node-migrate#76]
Hello, guys, I'm trying to run this migrate command `migrate create add-pets` but the problem is it is throwing me an error pointed out int the above title. I have installed it using yarn 

yarn add migrate 

but whenever I try to run the command it is throwing me the above error

OS: UBUNTU

**Comment by wesleytodd** [comment]
Hey @Gardezi1.  I dont use yarn, so am not sure what the issue is.  Can you post more information, like the specific output from the command line?

**Comment by Gardezi1** [comment]
@wesleytodd I was able to solve the problem can't remember how but I was able to solve it. So I should close this issue
