### ISSUE TITLE
Can't migrate on Windows

### ISSUE THREAD

**Issue by Alendorff** [tj/node-migrate#83]
I have set of migrations which works perfectly on linux systems, but when I try to run migrations on Windows machine I get the following:

```
{ProjectPath}>yarn run migrate
yarn run v1.2.1
$ node -r dotenv/config node_modules/.bin/migrate --state-file runtime/.migrate
{ProjectPath}\node_modules\.bin\migrate:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

This is `migrate` script command:

`"migrate": "node -r dotenv/config node_modules/.bin/migrate --state-file runtime/.migrate",`

**Comment by wesleytodd** [comment]
Hey @Alendorff.  I was actually going to release the `1.0.0` version this week.  Do you think you could try that?  You can install it now with `npm i migrate@next` or whatever the compatible yarn command is (sorry I dont use yarn).

**Comment by Alendorff** [comment]
Alas, but situation with 1.0.0-2 is exactly the same.

**Comment by wesleytodd** [comment]
Interesting.  Have you tried with npm?  Also what node version?

**Comment by Alendorff** [comment]
Yes, it's the same with npm. 
```

>npm -v
5.4.2

>yarn -v
1.2.1

>node -v
v8.7.0

```

**Comment by wesleytodd** [comment]
Ok, found it.  npm creates a `node_modules/.bin/migrate.cmd` for use on windows.  In my windows vm I tried adding a package.json script like this:

```
{
  "scripts": {
    "migrate": "migrate"
  }
}
```

Then ran:

```
> npm run migrate init
> npm run migrate
```

And that seemed to work.  Hope that helps.

**Comment by Alendorff** [comment]
Yes, thank you, it seems like simple `migrate` works fine. But in my script I wanted to preload environment variables by executing dotenv/config (`node -r dotenv/config`) module. Because I use some configs in migrations like db url, etc... But, unfortunately, it doesn't work on windows.

**Comment by LinusU** [comment]
Not really a solution, but db-migrate loads `.env` automatically (using dotenv) and I would personally like it if this module did the same. It's quite convenient, for exactly the use case you are using it for, and I believe it to be somewhat of a standard to have `.env` files...

**Comment by wesleytodd** [comment]
I think maybe since I don't use windows I don't understand the use case.  Can you not just do:

```
$ MY_DB_PASS=foo npm run migrate
```

Or any other method of setting env variables?

Would love to get input on how people want this to work.

**Comment by Alendorff** [comment]
@wesleytodd yes, of course it will work, but it's a bit inconvenient.

**Comment by wesleytodd** [comment]
Could you suggest what you would rather have?

**Comment by Alendorff** [comment]
@wesleytodd I would rather have .env file :)

**Comment by wesleytodd** [comment]
Can you elaborate?  Should it be loaded in with an `--env` flag?  Like `--env path/to/file`.  Where the file is like:

```
FOO=bar
BAZ=foz
```

I always used the system I am on to manage my environment variables, or just a small bash script wrapper during development if I need it.  I have never felt the need for a tool to support them directly, so I need more info on how you would want it to work.

**Comment by wesleytodd** [comment]
@LinusU mentioned this module: https://www.npmjs.com/package/dotenv

Is this what you are talking about?

**Comment by Alendorff** [comment]
Yes, `--env` flag could be a pretty usable for that case, I think. 
If we're talking about [dotenv library](https://github.com/motdotla/dotenv), then default path for `.env` file is a project root, but it's not mandatory, so, it's better to have an option to specify custom path. But should those `.env` files work by default - I don't know, it's up to you :) It would be convenient for me personally, but I can't say for everyone.

**Comment by Alendorff** [comment]
@wesleytodd yes, it's exactly what I meant.

**Comment by wesleytodd** [comment]
Awesome, ok.  This I can go on.  I just read through that module module's readme and it looks solid.  I will work on support for this.  Thanks for following up with me!
