### ISSUE TITLE
migrate --template-file stopped working after update to ^1.x

### ISSUE THREAD

**Issue by dananichev** [tj/node-migrate#94]
Running

```bash
migrate --template-file ./migrations/lib/template.js create test
```

leads to error:

```javascript
migrate --template-file ./migrations/lib/template.js

error: unknown option `--template-file'
```

0.2 works fine.

**Comment by wesleytodd** [comment]
Hey @dananichev.  I think it is just the order of the arguments that is causing this.  Previous to `v1` it used bespoke argument parsing.  Now it uses `commander`, which requires that the flags for a sub command come after the command name.  Sorry about the confusion.

I added a test for this flag while I was ensuring that it worked.  See #95.

**Comment by dananichev** [comment]
Hey @wesleytodd! Thanks for feedback. 

But in case of pre 1.0 versions we could use simple npm script 
```json
"migrate": "migrate --template-file ./migrations/lib/template.js",
```
and provide commands. For example:
```bash
# npm run migrate up
# npm run migrate create test
# npm run migrate down
```

In case of post 1.0 it is not possible. I mean you can't even add npm script for ``migrate create`` something due to changes mentioned above (even though only ``create`` needs ``--template-file``). 

So i guess my question is: how can it be handled after 1.0? 

Using
```bash
# (npx | npm run | etc) migrate create test-1 --template-file=./template.js
# (npx | npm run | etc) migrate create test-2 --template-file=./template.js
# (npx | npm run | etc) migrate create test-3 --template-file=./template.js
...
```
each time then you need to create new migration is not a good option.

**Comment by wesleytodd** [comment]
That is a good point.  The way I had done this is:

```
"migrate-create": "migrate create --template-file ./migrations/lib/template.js"
```

So you could then run:

```
$ npm run migrate-create foo
```

Does that work for you?

I really don't like the idea of adding a `.migrate.yaml` if I can avoid it.

**Comment by dananichev** [comment]
@wesleytodd i wanted to avoid creating different script commands for each operation but for now i have no other choice it seems :)

Thanks anyways!

**Comment by wesleytodd** [comment]
@dananichev We can work on a better solution, but I think it would involve support from `commander`.  IMO it seems reasonable to forward flags from the parent command to the children commands, but this is not currently what it does.  I will dig around over there and see if there are any issues or PR's to add this feature.

**Comment by LinusU** [comment]
Potentially a bit annoying to switch so soon again, but I personally *love* [neodoc](https://github.com/felixSchl/neodoc), and they have an option, `laxPlacement`, just for this.

**Comment by wesleytodd** [comment]
I am not totally against it, but only if someone else does it :)

TBH it seems like a great addition to `commander`, so if someone did it there we could simply update here.  Which would clearly be the simplest way forward for this project.  But again, I am probably not going to be able to carve out a chunk of time for this soon as I just moved and am starting a new job.

**Comment by LinusU** [comment]
> [...] I just moved and am starting a new job.

Congratulations! 🎉 🎉 good luck on the new job 👏
