### ISSUE TITLE
The framework does not work when used with Promise.all

### ISSUE THREAD

**Issue by XVincentX** [tj/node-migrate#96]
In case you're returning `Promise.all([])` instead of a single promise, the return value is an array instead of an object.

In case all the promises are resolved correctly, the return value is `[undefined,undefined,undefined]`.

This is clashing with [this part](https://github.com/tj/node-migrate/blob/master/lib/migrate.js#L52) that requires the error object to be undefined.

The catch handler should probably be a different one than the completion handler, so we do not incur in these situations.

I can provide a PR if you appreciate.

**Comment by LinusU** [comment]
Yeah, that seems like a typo. PR welcome!
