### ISSUE TITLE
Missing migration file

### ISSUE THREAD

**Issue by christianbundy** [tj/node-migrate#98]
I'm working with a distributed team on an application that depends on node-migrate, but we're running into an issue when we switch from a feature branch back to master (which is missing the migration(s) from the feature branch).

```console
$ git init
Initialized empty Git repository in /home/christianbundy/work/node-migrate-repro/.git/
$ echo ".migrate" > .gitignore
$ migrate --version
1.1.1
$ migrate init
  migrations dir : /home/christianbundy/work/node-migrate-repro/migrations
$ migrate create a
  create : /home/christianbundy/work/node-migrate-repro/migrations/1515783157036-a.js
$ migrate up
  up : 1515783157036-a.js
  migration : complete
$ git add -A
$ git commit -m "Initial commit"
[master (root-commit) aca1d14] Initial commit
 2 files changed, 10 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 migrations/1515783157036-a.js
$ git checkout -b new-feature
Switched to a new branch 'new-feature'
$ migrate create b
  create : /home/christianbundy/work/node-migrate-repro/migrations/1515783180837-b.js
$ migrate up
  up : 1515783180837-b.js
  migration : complete
$ git add -A
$ git commit -m "New feature"
[new-feature 2bd3e51] New feature
 1 file changed, 9 insertions(+)
 create mode 100644 migrations/1515783180837-b.js
$ migrate down
  down : 1515783180837-b.js
  down : 1515783157036-a.js
  migration : complete
$ git checkout master
Switched to branch 'master'
$ migrate up
  error : Error: Missing migration file: 1515783180837-b.js
```

[![asciicast](https://asciinema.org/a/aLTbJ1WH93IBv073hP36C3wYm.png)](https://asciinema.org/a/aLTbJ1WH93IBv073hP36C3wYm)

I imagined that `migrate down` would remove the state file after a successful down migration, but it looks like it's still keeping track of all of the previous migrations (even though they've been taken down). Is there a better way of doing this?

Thanks so much for your work on this project!

**Comment by wesleytodd** [comment]
Hey @christianbundy. I think this is a bug.  Because you have run `down` before switching back.  If you had not run `migrate down`, it would be the expected behavior (see this test: https://github.com/tj/node-migrate/blob/master/test/integration.js#L64-L102).  In this case, it should only care that it can't load it if it thinks it had been run previously.  Im looking at a fix right now.

**Comment by wesleytodd** [comment]
I think the fix is to add a check that `m.timestamp` is not `null` here: https://github.com/tj/node-migrate/blob/master/lib/load-migrations.js#L55

If you want to submit a PR for this I will merge and publish asap.  If not I will fix this when I get home tonight.

**Comment by christianbundy** [comment]
That looks great, sorry I didn't get back to you! Thanks for your help.
